# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-05-08 15:47:39
"""
import arcpy

def Model1():  # net

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    rockfall_net = "rockfall_net"

    # Process: Create Fishnet (Create Fishnet) (management)
    teeasd = "C:\\Users\\User1\\Documents\\ArcGIS\\Default.gdb\\teeasd"
    tee_label = arcpy.management.CreateFishnet(out_feature_class=teeasd, origin_coord="358151.52583837 4683332.0119661", y_axis_coord="358151.52583837 4683342.0119661", cell_width=1, cell_height=1, number_rows=None, number_columns=None, corner_coord="359270.52583837 4684019.0119661", labels="LABELS", template="C:\\SAGA-GIS\\RF3D_script\\INPUT\\dem.asc", geometry_type="POLYGON")[0]

    # Process: Spatial Join (Spatial Join) (analysis)
    tee_SpatialJoin = "C:\\Users\\User1\\Documents\\ArcGIS\\Default.gdb\\tee_SpatialJoin"
    arcpy.analysis.SpatialJoin(target_features=teeasd, join_features=rockfall_net, out_feature_class=tee_SpatialJoin, join_operation="JOIN_ONE_TO_ONE", join_type="KEEP_ALL", field_mapping="net_height \"net_height\" true true false 10 Long 0 10,First,#,rockfall_net,net_height,-1,-1;net_number \"net_number\" true true false 10 Long 0 10,First,#,rockfall_net,net_number,-1,-1;net_energy \"net_energy\" true true false 10 Long 0 10,First,#,rockfall_net,net_energy,-1,-1", match_option="INTERSECT", search_radius="", distance_field_name="")

    # Process: Feature to Raster (9) (Feature to Raster) (conversion)
    Feature_DEL_168 = "C:\\Users\\User1\\Documents\\ArcGIS\\Default.gdb\\Feature_DEL_168"
    arcpy.conversion.FeatureToRaster(in_features=tee_SpatialJoin, field="net_height", out_raster=Feature_DEL_168, cell_size="1")
    Feature_DEL_168 = arcpy.Raster(Feature_DEL_168)

    # Process: Raster to ASCII (10) (Raster to ASCII) (conversion)
    net_height_ASC = "C:\\SAGA-GIS\\RF3D_script\\OUTPUT\\net_height.ASC"
    arcpy.conversion.RasterToASCII(in_raster=Feature_DEL_168, out_ascii_file=net_height_ASC)

    # Process: Feature to Raster (2) (Feature to Raster) (conversion)
    Feature_DEL_17745 = "C:\\Users\\User1\\Documents\\ArcGIS\\Default.gdb\\Feature_DEL_17745"
    arcpy.conversion.FeatureToRaster(in_features=tee_SpatialJoin, field="net_number", out_raster=Feature_DEL_17745, cell_size="1")
    Feature_DEL_17745 = arcpy.Raster(Feature_DEL_17745)

    # Process: Raster to ASCII (3) (Raster to ASCII) (conversion)
    net_number_ASC = "C:\\SAGA-GIS\\RF3D_script\\OUTPUT\\net_number.ASC"
    arcpy.conversion.RasterToASCII(in_raster=Feature_DEL_17745, out_ascii_file=net_number_ASC)

    # Process: Feature to Raster (8) (Feature to Raster) (conversion)
    Feature_DEL_16676 = "C:\\Users\\User1\\Documents\\ArcGIS\\Default.gdb\\Feature_DEL_16676"
    arcpy.conversion.FeatureToRaster(in_features=tee_SpatialJoin, field="net_energy", out_raster=Feature_DEL_16676, cell_size="1")
    Feature_DEL_16676 = arcpy.Raster(Feature_DEL_16676)

    # Process: Raster to ASCII (Raster to ASCII) (conversion)
    net_energy_ASC = "C:\\SAGA-GIS\\RF3D_script\\OUTPUT\\net_energy.ASC"
    arcpy.conversion.RasterToASCII(in_raster=Feature_DEL_16676, out_ascii_file=net_energy_ASC)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"D:\R_F_chiatura\GIS PROJECT\Tchiatura_rockfall_Hazard.gdb", workspace=r"D:\R_F_chiatura\GIS PROJECT\Tchiatura_rockfall_Hazard.gdb"):
        Model1()
