# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-05-08 15:46:35
"""
import arcpy
from sys import argv

def workspace(Cell_Size_Width=5, Cell_Size_Height=5, Geometry_Type="POLYGON", same_as_dem="C:\\SAGA-GIS\\RF3D_script\\OUTPUT\\dem.asc", DEL_SpatialJoin="C:\\Users\\User1\\Documents\\ArcGIS\\Default.gdb\\DEL_SpatialJoin"):  # forest

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\nk\OneDrive\Documents\ArcGIS\Default.gdb", workspace=r"C:\Users\nk\OneDrive\Documents\ArcGIS\Default.gdb"):
        forest_shp = "C:\\SAGA-GIS\\RF3D_script\\INPUT\\forest.shp"

        # Process: Create Fishnet (Create Fishnet) (management)
        DEL1_shp = "C:\\SAGA-GIS\\RF3D_script\\OUTPUT\\DEL1.shp"
        fishnet_label_shp = arcpy.management.CreateFishnet(out_feature_class=DEL1_shp, origin_coord="357572.52583837 4683027.1081301", y_axis_coord="357572.52583837 4683037.1081301", cell_width=Cell_Size_Width, cell_height=Cell_Size_Height, number_rows=None, number_columns=None, corner_coord="360142.39876237 4684374.5119661", labels="NO_LABELS", template=same_as_dem, geometry_type=Geometry_Type)[0]

        # Process: Spatial Join (Spatial Join) (analysis)
        arcpy.analysis.SpatialJoin(target_features=DEL1_shp, join_features=forest_shp, out_feature_class=DEL_SpatialJoin, join_operation="JOIN_ONE_TO_ONE", join_type="KEEP_ALL", field_mapping="Id \"Id\" true true false 6 Long 0 6,First,#,C:\\SAGA-GIS\\RF3D_script\\OUTPUT\\DEL1.shp,Id,-1,-1;nrtrees \"nrtrees\" true true false 10 Long 0 10,First,#,C:\\SAGA-GIS\\RF3D_script\\INPUT\\forest.shp,nrtrees,-1,-1;dbhmean \"dbhmean\" true true false 13 Float 0 0,First,#,C:\\SAGA-GIS\\RF3D_script\\INPUT\\forest.shp,dbhmean,-1,-1;dbhstd \"dbhstd\" true true false 13 Float 0 0,First,#,C:\\SAGA-GIS\\RF3D_script\\INPUT\\forest.shp,dbhstd,-1,-1;conif_perc \"conif_perc\" true true false 5 Long 0 5,First,#,C:\\SAGA-GIS\\RF3D_script\\INPUT\\forest.shp,conif_perc,-1,-1", match_option="INTERSECT", search_radius="", distance_field_name="")

        # Process: Feature to Raster (3) (Feature to Raster) (conversion)
        Feature_DEL_145661 = "C:\\Users\\User1\\Documents\\ArcGIS\\Default.gdb\\Feature_DEL_145661"
        arcpy.conversion.FeatureToRaster(in_features=DEL_SpatialJoin, field="nrtrees", out_raster=Feature_DEL_145661, cell_size="5")
        Feature_DEL_145661 = arcpy.Raster(Feature_DEL_145661)

        # Process: Raster to ASCII (4) (Raster to ASCII) (conversion)
        nrtrees_ASC = "C:\\SAGA-GIS\\RF3D_script\\OUTPUT\\nrtrees.ASC"
        arcpy.conversion.RasterToASCII(in_raster=Feature_DEL_145661, out_ascii_file=nrtrees_ASC)

        # Process: Feature to Raster (5) (Feature to Raster) (conversion)
        Feature_DEL_1546 = "C:\\Users\\User1\\Documents\\ArcGIS\\Default.gdb\\Feature_DEL_1546"
        arcpy.conversion.FeatureToRaster(in_features=DEL_SpatialJoin, field="dbhmean", out_raster=Feature_DEL_1546, cell_size="5")
        Feature_DEL_1546 = arcpy.Raster(Feature_DEL_1546)

        # Process: Raster to ASCII (6) (Raster to ASCII) (conversion)
        dbhmean_ASC = "C:\\SAGA-GIS\\RF3D_script\\OUTPUT\\dbhmean.ASC"
        arcpy.conversion.RasterToASCII(in_raster=Feature_DEL_1546, out_ascii_file=dbhmean_ASC)

        # Process: Feature to Raster (7) (Feature to Raster) (conversion)
        Feature_DEL_16456 = "C:\\Users\\User1\\Documents\\ArcGIS\\Default.gdb\\Feature_DEL_16456"
        arcpy.conversion.FeatureToRaster(in_features=DEL_SpatialJoin, field="dbhstd", out_raster=Feature_DEL_16456, cell_size="5")
        Feature_DEL_16456 = arcpy.Raster(Feature_DEL_16456)

        # Process: Raster to ASCII (8) (Raster to ASCII) (conversion)
        dbhstd_ASC = "C:\\SAGA-GIS\\RF3D_script\\OUTPUT\\dbhstd.ASC"
        arcpy.conversion.RasterToASCII(in_raster=Feature_DEL_16456, out_ascii_file=dbhstd_ASC)

        # Process: Feature to Raster (9) (Feature to Raster) (conversion)
        Feature_DEL_168 = "C:\\Users\\User1\\Documents\\ArcGIS\\Default.gdb\\Feature_DEL_168"
        arcpy.conversion.FeatureToRaster(in_features=DEL_SpatialJoin, field="conif_perc", out_raster=Feature_DEL_168, cell_size="5")
        Feature_DEL_168 = arcpy.Raster(Feature_DEL_168)

        # Process: Raster to ASCII (10) (Raster to ASCII) (conversion)
        conif_percent_ASC = "C:\\SAGA-GIS\\RF3D_script\\OUTPUT\\conif_percent.ASC"
        arcpy.conversion.RasterToASCII(in_raster=Feature_DEL_168, out_ascii_file=conif_percent_ASC)

if __name__ == '__main__':
    workspace(*argv[1:])
