# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-05-08 15:46:00
"""
import arcpy
from sys import argv

def Model(Cell_Size_Width=5, Cell_Size_Height=5, Geometry_Type="POLYGON", same_as_dem="357572.52583837 4683027.5119661 360142.02583837 4684374.5119661 PROJCS[\"WGS_1984_UTM_Zone_38N\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",45.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]],VERTCS[\"Unknown VCS\",VDATUM[\"Unknown\"],PARAMETER[\"Vertical_Shift\",0.0],PARAMETER[\"Direction\",1.0],UNIT[\"Meter\",1.0]]", DEL_SpatialJoinHU="C:\\Users\\User1\\Documents\\ArcGIS\\Default.gdb\\DEL_SpatialJoinHU", input_terrain1="terrain"):  # terrain

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False


    # Process: Create Fishnet (Create Fishnet) (management)
    DEL_shp = "C:\\SAGA-GIS\\RF3D_script\\OUTPUT\\DEL.shp"
    with arcpy.EnvManager(extent=same_as_dem):
        fishnet_label_shp = arcpy.management.CreateFishnet(out_feature_class=DEL_shp, origin_coord="357572.52583837 4683027.5119661", y_axis_coord="357572.52583837 4683037.5119661", cell_width=Cell_Size_Width, cell_height=Cell_Size_Height, number_rows=None, number_columns=None, corner_coord="360142.02583837 4684374.5119661", labels="NO_LABELS", template=same_as_dem, geometry_type=Geometry_Type)[0]

    # Process: Spatial Join (Spatial Join) (analysis)
    arcpy.analysis.SpatialJoin(target_features=DEL_shp, join_features=input_terrain1, out_feature_class=DEL_SpatialJoinHU, join_operation="JOIN_ONE_TO_ONE", join_type="KEEP_ALL", field_mapping="Id \"Id\" true true false 6 Long 0 6,First,#,C:\\SAGA-GIS\\RF3D_script\\OUTPUT\\DEL.shp,Id,-1,-1;ROCDENSITY \"ROCDENSITY\" true true false 19 Double 0 0,First,#,terrain,ROCDENSITY,-1,-1;D1 \"d1\" true true false 19 Double 0 0,First,#,terrain,D1,-1,-1;D2 \"d2\" true true false 19 Double 0 0,First,#,terrain,D2,-1,-1;D3 \"d3\" true true false 19 Double 0 0,First,#,terrain,D3,-1,-1;ROCDENSITY \"ROCDENSITY\" true true false 19 Double 0 0,First,#,terrain,ROCDENSITY,-1,-1;BLSHAPE \"BLSHAPE\" true true false 19 Double 0 0,First,#,terrain,BLSHAPE,-1,-1;RG70 \"RG70\" true true false 19 Double 0 0,First,#,terrain,RG70,-1,-1;RG20 \"RG20\" true true false 19 Double 0 0,First,#,terrain,RG20,-1,-1;RG10 \"RG10\" true true false 19 Double 0 0,First,#,terrain,RG10,-1,-1;SOILTYPE \"SOILTYPE\" true true false 19 Double 0 0,First,#,terrain,SOILTYPE,-1,-1;Shape_Leng \"Shape_Leng\" true true false 19 Double 0 0,First,#,terrain,Shape_Leng,-1,-1;Shape_Area \"Shape_Area\" true true false 19 Double 0 0,First,#,terrain,Shape_Area,-1,-1", match_option="INTERSECT", search_radius="-0.1 Meters", distance_field_name="")

    # Process: Feature to Raster (Feature to Raster) (conversion)
    Feature_DEL_1333 = "C:\\Users\\User1\\Documents\\ArcGIS\\Default.gdb\\Feature_DEL_1333"
    arcpy.conversion.FeatureToRaster(in_features=DEL_SpatialJoinHU, field="D1", out_raster=Feature_DEL_1333, cell_size="1.5")
    Feature_DEL_1333 = arcpy.Raster(Feature_DEL_1333)

    # Process: Raster to ASCII (2) (Raster to ASCII) (conversion)
    d1_ASC = "C:\\SAGA-GIS\\RF3D_script\\OUTPUT\\d1.asc"
    arcpy.conversion.RasterToASCII(in_raster=Feature_DEL_1333, out_ascii_file=d1_ASC)

    # Process: Feature to Raster (3) (Feature to Raster) (conversion)
    Feature_DEL_14566 = "C:\\Users\\User1\\Documents\\ArcGIS\\Default.gdb\\Feature_DEL_14566"
    arcpy.conversion.FeatureToRaster(in_features=DEL_SpatialJoinHU, field="ROCDENSITY", out_raster=Feature_DEL_14566, cell_size="1.5")
    Feature_DEL_14566 = arcpy.Raster(Feature_DEL_14566)

    # Process: Raster to ASCII (4) (Raster to ASCII) (conversion)
    ROCKDENSITY_ASC = "C:\\SAGA-GIS\\RF3D_script\\OUTPUT\\ROCKDENSITY.ASC"
    arcpy.conversion.RasterToASCII(in_raster=Feature_DEL_14566, out_ascii_file=ROCKDENSITY_ASC)

    # Process: Feature to Raster (4) (Feature to Raster) (conversion)
    Feature_DEL_177 = "C:\\Users\\User1\\Documents\\ArcGIS\\Default.gdb\\Feature_DEL_177"
    arcpy.conversion.FeatureToRaster(in_features=DEL_SpatialJoinHU, field="D3", out_raster=Feature_DEL_177, cell_size="1.5")
    Feature_DEL_177 = arcpy.Raster(Feature_DEL_177)

    # Process: Raster to ASCII (5) (Raster to ASCII) (conversion)
    d3_ASC = "C:\\SAGA-GIS\\RF3D_script\\OUTPUT\\d3.asc"
    arcpy.conversion.RasterToASCII(in_raster=Feature_DEL_177, out_ascii_file=d3_ASC)

    # Process: Feature to Raster (5) (Feature to Raster) (conversion)
    Feature_DEL_1546 = "C:\\Users\\User1\\Documents\\ArcGIS\\Default.gdb\\Feature_DEL_1546"
    arcpy.conversion.FeatureToRaster(in_features=DEL_SpatialJoinHU, field="RG70", out_raster=Feature_DEL_1546, cell_size="1.5")
    Feature_DEL_1546 = arcpy.Raster(Feature_DEL_1546)

    # Process: Raster to ASCII (6) (Raster to ASCII) (conversion)
    RG70_ASC = "C:\\SAGA-GIS\\RF3D_script\\OUTPUT\\rg70.asc"
    arcpy.conversion.RasterToASCII(in_raster=Feature_DEL_1546, out_ascii_file=RG70_ASC)

    # Process: Feature to Raster (6) (Feature to Raster) (conversion)
    Feature_DEL_177776 = "C:\\Users\\User1\\Documents\\ArcGIS\\Default.gdb\\Feature_DEL_177776"
    arcpy.conversion.FeatureToRaster(in_features=DEL_SpatialJoinHU, field="BLSHAPE", out_raster=Feature_DEL_177776, cell_size="1.5")
    Feature_DEL_177776 = arcpy.Raster(Feature_DEL_177776)

    # Process: Raster to ASCII (7) (Raster to ASCII) (conversion)
    BLSHAPE_ASC = "C:\\SAGA-GIS\\RF3D_script\\OUTPUT\\blshape.asc"
    arcpy.conversion.RasterToASCII(in_raster=Feature_DEL_177776, out_ascii_file=BLSHAPE_ASC)

    # Process: Feature to Raster (7) (Feature to Raster) (conversion)
    Feature_DEL_16456 = "C:\\Users\\User1\\Documents\\ArcGIS\\Default.gdb\\Feature_DEL_16456"
    arcpy.conversion.FeatureToRaster(in_features=DEL_SpatialJoinHU, field="RG20", out_raster=Feature_DEL_16456, cell_size="1.5")
    Feature_DEL_16456 = arcpy.Raster(Feature_DEL_16456)

    # Process: Raster to ASCII (8) (Raster to ASCII) (conversion)
    RG20_ASC = "C:\\SAGA-GIS\\RF3D_script\\OUTPUT\\rg20.asc"
    arcpy.conversion.RasterToASCII(in_raster=Feature_DEL_16456, out_ascii_file=RG20_ASC)

    # Process: Feature to Raster (8) (Feature to Raster) (conversion)
    Feature_DEL_16676 = "C:\\Users\\User1\\Documents\\ArcGIS\\Default.gdb\\Feature_DEL_16676"
    arcpy.conversion.FeatureToRaster(in_features=DEL_SpatialJoinHU, field="RG10", out_raster=Feature_DEL_16676, cell_size="1.5")
    Feature_DEL_16676 = arcpy.Raster(Feature_DEL_16676)

    # Process: Raster to ASCII (9) (Raster to ASCII) (conversion)
    RG10_ASC = "C:\\SAGA-GIS\\RF3D_script\\OUTPUT\\rg10.asc"
    arcpy.conversion.RasterToASCII(in_raster=Feature_DEL_16676, out_ascii_file=RG10_ASC)

    # Process: Feature to Raster (9) (Feature to Raster) (conversion)
    Feature_DEL_168 = "C:\\Users\\User1\\Documents\\ArcGIS\\Default.gdb\\Feature_DEL_168"
    arcpy.conversion.FeatureToRaster(in_features=DEL_SpatialJoinHU, field="SOILTYPE", out_raster=Feature_DEL_168, cell_size="1.5")
    Feature_DEL_168 = arcpy.Raster(Feature_DEL_168)

    # Process: Raster to ASCII (10) (Raster to ASCII) (conversion)
    SOILTYPE_ASC = "C:\\SAGA-GIS\\RF3D_script\\OUTPUT\\soiltype.asc"
    arcpy.conversion.RasterToASCII(in_raster=Feature_DEL_168, out_ascii_file=SOILTYPE_ASC)

    # Process: Feature to Raster (2) (Feature to Raster) (conversion)
    Feature_DEL_17745 = "C:\\Users\\User1\\Documents\\ArcGIS\\Default.gdb\\Feature_DEL_17745"
    arcpy.conversion.FeatureToRaster(in_features=DEL_SpatialJoinHU, field="D2", out_raster=Feature_DEL_17745, cell_size="1.5")
    Feature_DEL_17745 = arcpy.Raster(Feature_DEL_17745)

    # Process: Raster to ASCII (3) (Raster to ASCII) (conversion)
    d2_ASC = "C:\\SAGA-GIS\\RF3D_script\\OUTPUT\\d2.asc"
    arcpy.conversion.RasterToASCII(in_raster=Feature_DEL_17745, out_ascii_file=d2_ASC)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"D:\R_F_chiatura\GIS PROJECT\Tchiatura_rockfall_Hazard.gdb", workspace=r"D:\R_F_chiatura\GIS PROJECT\Tchiatura_rockfall_Hazard.gdb"):
        Model(*argv[1:])
